# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d326c29306d0a2a600ece33dfb844c30dd756f3016813e389674c0459ab1c8b9f547015928abc369ab5e8e4f8a3eb35a0ee3a8493c99ca114035d5d899ed51df

test:
  secret_key_base: 05b00ac9b8491592909a9bc038c466d724d6a3de54119f2d2eea6ba40ee08c87be56db292a729cde043d1da9002e2ad8e7923a981ddf8ab8f471d3b8d1ec217f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
